# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆)
(**hint**: import … as …)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
np.__version__



'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)
(**hint**: np.zeros)

In [ ]:
res=np.zeros(10)
print(res)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)
(**hint**: size, itemsize)

In [ ]:
res=np.array([10,20,30])
print(res.size)

3


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)
(**hint**: np.info)

In [ ]:
res=np.info([10,20,40])
print(res)


Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
(**hint**: array\[4\])

In [ ]:
res=np.zeros(10)
res[4]=1
print(res)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)
(**hint**: array\[::-1\])

In [ ]:
a=np.arange(10,50)
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
(**hint**: reshape)

In [ ]:
a=np.arange(9)

print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
(**hint**: np.nonzero)

In [ ]:
a=np.array([1,2,0,0,4,0])
res=np.nonzero(a)
print(res)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
(**hint**: np.eye)

In [ ]:
res=np.eye(3,3)
print(res)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
(**hint**: np.random.random)

In [ ]:
res=np.random.random((3,3,3))
print(res)

[[[0.37444653 0.88209696 0.13190597]
  [0.85180018 0.23048552 0.15144701]
  [0.23237033 0.4592105  0.79374697]]

 [[0.2858821  0.20478147 0.60648757]
  [0.056578   0.64334584 0.63929   ]
  [0.66473042 0.08884353 0.36407426]]

 [[0.43965979 0.63954367 0.37180364]
  [0.21448252 0.18967328 0.73950774]
  [0.73304349 0.67103432 0.31598424]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print(a)
print("min array with random value is",a.min())
print("max array with random value is ",a.max())

[[0.02506941 0.72112963 0.48361894 0.91518616 0.41163177 0.69799483
  0.67088605 0.51052688 0.98158566 0.71000656]
 [0.32422889 0.30244768 0.45652825 0.79250034 0.81266231 0.79462626
  0.63181779 0.00982682 0.91895698 0.51179114]
 [0.00907205 0.18665025 0.9932957  0.20647591 0.32239208 0.11670891
  0.02540762 0.3594289  0.84347551 0.25935081]
 [0.97233323 0.57379446 0.33900195 0.77142052 0.8415989  0.17975862
  0.29800669 0.74715409 0.65665468 0.03588466]
 [0.68167481 0.55081229 0.79882798 0.45847563 0.12047169 0.36567867
  0.7425493  0.52246402 0.6279187  0.33441972]
 [0.04014005 0.05446106 0.01025361 0.42279371 0.95211415 0.03181295
  0.61541437 0.9635453  0.91603707 0.99540044]
 [0.85077519 0.51994196 0.90849805 0.65407513 0.01117168 0.28283698
  0.68787797 0.37399546 0.60112557 0.27928638]
 [0.13665632 0.40023491 0.95203102 0.54756582 0.63926693 0.69982919
  0.28691597 0.54942167 0.15914805 0.6177448 ]
 [0.90229061 0.97535378 0.28222966 0.89840556 0.69297171 0.63141803
  0.05279985

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
(**hint**: mean)

In [ ]:
res=np.random.random(30)
print(res.mean())

0.48075709243406367


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
res=np.ones((3,3))
res[1:-1,1:-1]=0
print(res)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
(**hint**: np.pad)

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
boder=np.pad(arr,pad_width=1,mode='constant',constant_values=0
             )
print(boder)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)




nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
(**hint**: np.diag)

In [ ]:
arr=np.diag((1,2,3,4))
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
(**hint**: array\[::2\])

In [ ]:
arr=np.ones((8,8))
print(arr[::2])


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
(**hint**: np.unravel_index)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
(**hint**: np.tile)

In [ ]:
check=np.tile([[0,1],[1,0]],(8,8))
print(check )

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)
(**hint**: (x - min) / (max - min))

In [ ]:
arr=np.random.rand(5,5)
res=(arr-arr.min())/(arr.max()-arr.min())
print(res)

[[0.70785121 0.38930375 0.41848181 0.96340709 1.        ]
 [0.85022302 0.91673115 0.90976289 0.8591496  0.        ]
 [0.42039717 0.35254559 0.26748239 0.51551408 0.01290276]
 [0.83172052 0.94660395 0.89475254 0.43654372 0.4000581 ]
 [0.47057479 0.05571283 0.99541876 0.23660143 0.80580623]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
(**hint**: np.dtype)

In [ ]:
import numpy as np

color=np.dtype([
    ('R',np.uint8),
    ('G',np.uint8),
    ('B',np.uint8),
    ('A',np.uint8)
])

print(color)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
(**hint**: np.dot | @)

In [ ]:
a=np.random.rand(5,3)
b=np.random.rand(3,2)

c=np.dot(a,b)
print(c)
# res=a@b



[[0.35343461 0.64941698]
 [0.2566391  0.53314595]
 [0.56320299 0.92749719]
 [0.69431072 1.08623543]
 [0.16034283 0.57181211]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
(**hint**: >, <=)

In [ ]:
arr=np.array([10,20,30,40,50,60,70,80,90])
arr[(arr>3) & (arr<=8)]
print(arr)

[10 20 30 40 50 60 70 80 90]


#### 26. What is the output of the following script? (★☆☆)
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5])

res = Z ** Z
print("Z**Z =", res)


shift_res=2<<Z>>2
print("2<<Z>>2=",shift_res)

comparison_res = Z < -Z
print("Z < -Z =", comparison_res)


complex_res = 1j * Z
print("1j * Z =", complex_res)


division_res = Z / 1 / 1
print("Z / 1 / 1 =", division_res)


Z**Z = [   1    4   27  256 3125]
2 << Z >> 2 = [ 1  2  4  8 16]
Z < -Z = [False False False False False]
1j * Z = [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
Z / 1 / 1 = [1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [176]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

np.int64(0)

#### 29. How to round away from zero a float array ? (★☆☆)
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
import numpy as np
arr=np.random.uniform([0.0,0.0,0.0])
res=np.copysign(np.ceil(np.abs(arr)),arr)

print("Before the round value ",arr)
print("After the round value ",res)

Before the round value  [0.83510064 0.33333823 0.66369574]
After the round value  [1. 1. 1.]


#### 30. How to find common values between two arrays? (★☆☆)
(**hint**: np.intersect1d)

In [ ]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([1,4,5,6,2])

res=np.intersect1d(a,b)
print(res)

[1 2 4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
(**hint**: np.seterr, np.errstate)

In [ ]:
arr=np.seterr(all='ignore')
print(arr)

arr2=np.errstate(all='ignore')
a=np.array([1,0,-1])
b=a/0
print(b)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}
[ inf  nan -inf]


#### 32. Is the following expressions true? (★☆☆)
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(9))
print(np.emath.sqrt(-1))

b=np.sqrt(-1)==np.emath.sqrt(-1)
print(b)



3.0
1j
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
import numpy as np

today=np.datetime64('today')
yesterday=today-np.timedelta64(1,'D')
tomorrow=today+np.timedelta64(1,'D')

print("Today date is ",today)
print("yesterday date was",yesterday)
print("Tomorrow date will be ",tomorrow)

Today date is  2026-01-24
yesterday date was 2026-01-23
Tomorrow date will be  2026-01-25


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
date=np.arange(np.datetime64('2026-01-01'),('2026-02-01'),dtype='datetime64[D]')
print(date)
print(len(date))



['2026-01-01' '2026-01-02' '2026-01-03' '2026-01-04' '2026-01-05'
 '2026-01-06' '2026-01-07' '2026-01-08' '2026-01-09' '2026-01-10'
 '2026-01-11' '2026-01-12' '2026-01-13' '2026-01-14' '2026-01-15'
 '2026-01-16' '2026-01-17' '2026-01-18' '2026-01-19' '2026-01-20'
 '2026-01-21' '2026-01-22' '2026-01-23' '2026-01-24' '2026-01-25'
 '2026-01-26' '2026-01-27' '2026-01-28' '2026-01-29' '2026-01-30'
 '2026-01-31']
31


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.array([12.,13.,14.,15.])
B=np.array([6.,7.,9.,10.])

np.add(A,B,out=A)

np.negative(B,out=B)

# np.multiply(A,B,out=A)

np.divide(A,2, out=B)

array([ 9. , 10. , 11.5, 12.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
n=np.random.uniform([-10,20,5])
print(n)


p=n-(n%2)
print("Random percentage is",p)

f=np.floor(n)
print("random floor value is ",f)

c=np.ceil(n)
print("random ceil value is ",c)

s=n.astype(int)
print(s)

t=np.trunc(n)
print(t)




[-1.08980079 15.46097972  2.38414971]
Random percentage is [-2. 14.  2.]
random floor value is  [-2. 15.  2.]
random ceil value is  [-1. 16.  3.]
[-1 15  2]
[-1. 15.  2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
(**hint**: np.arange)

In [ ]:
arr=np.arange(5).reshape(1,5)
arr=np.repeat(arr,5,axis=0)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(**hint**: np.linspace)

In [ ]:
arr=np.linspace(0,1,10)[1:-1]
print(arr)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


#### 40. Create a random vector of size 10 and sort it (★★☆)
(**hint**: sort)

In [ ]:
arr=np.random.random(10)
arr.sort()
print(arr)


[0.03883008 0.12118732 0.18981763 0.24181886 0.37791407 0.54018512
 0.57473557 0.83280922 0.87457301 0.93431434]
