In [5]:
"""
Broadcasting-method:
broadcasting-method is a powerful mechasim tool that allows numpy to work with
different shape when performing the airthmetic operation.
* Ensure the different shape array must have no of rows==No of columns.
"""
import numpy as np
x=np.array([[1,2,4,],[10,20,30],[50,60,70]])
y=np.array([5,10,15])

z=x+y
print(c)

[[ 6 12 19]
 [15 30 45]
 [55 70 85]]


In [9]:
#Copy an a array
# np.copy is used when we make any changes in new array it doesn't impact on the old array's
a=np.array([1,2,4])
b=a.copy()
print(b)

b[1]=5
print(b)

[1 2 4]
[1 5 4]


In [11]:
# Interview question
# generate an array of zeros with 2 rows nd 3 columns
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#generate an array of ones with 2 rows nd 3 columns
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# generate an array of specific with 2 rows nd 3 columns
s=np.full((2,3),3)
print(s)

[[3 3 3]
 [3 3 3]]


In [15]:
# generate an array of identity matrix.
e=np.eye(4)
print(e) # output is digonals formats

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# #Revision the numpy=methods
# 1.create an array--> np.array()
# 2.create row and columns in array --> np.shape()
# 3.check the dimension --> np.ndim()
# 4.check data type --> np.dtype()
# 5.check the number of element in the array --> np.size
# 6.how to apply the dot products on arrays --> np.dot(arr1,arr2)
# 7.creaete boolean indexing on array --> arr>condition
# 8.how to apply condition in array --> np.where(logic,true,false)
# 9.compute the indexs where condition is true -->np.argwhere(logic)  
# 10.apply transpose --> arr.T
# 11. CHECK the diagonal elements --> np.diag()
# 12.compute inverse of an array --> np.linalg.inv()
# 13.how to reshape an array --> np.reshape(rows,col)
# 14.concatenate 2 array --> np.concatenate((arr1,arr2),axis=0/1)
# 15.how to copy an array --> np.copy()