In [5]:
"""
Broadcasting-method:
broadcasting-method is a powerful mechasim tool that allows numpy to work with
different shape when performing the airthmetic operation.
* Ensure the different shape array must have no of rows==No of columns.
"""
import numpy as np
x=np.array([[1,2,4,],[10,20,30],[50,60,70]])
y=np.array([5,10,15])

z=x+y
print(c)

[[ 6 12 19]
 [15 30 45]
 [55 70 85]]


In [9]:
#Copy an a array
# np.copy is used when we make any changes in new array it doesn't impact on the old array's
a=np.array([1,2,4])
b=a.copy()
print(b)

b[1]=5
print(b)

[1 2 4]
[1 5 4]


In [11]:
# Interview question
# generate an array of zeros with 2 rows nd 3 columns
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#generate an array of ones with 2 rows nd 3 columns
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# generate an array of specific with 2 rows nd 3 columns
s=np.full((2,3),3)
print(s)

[[3 3 3]
 [3 3 3]]


In [15]:
# generate an array of identity matrix.
e=np.eye(4)
print(e) # output is digonals formats

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# #Revision the numpy=methods
# 1.create an array--> np.array()
# 2.create row and columns in array --> np.shape()
# 3.check the dimension --> np.ndim()
# 4.check data type --> np.dtype()
# 5.check the number of element in the array --> np.size
# 6.how to apply the dot products on arrays --> np.dot(arr1,arr2)
# 7.creaete boolean indexing on array --> arr>condition
# 8.how to apply condition in array --> np.where(logic,true,false)
# 9.compute the indexs where condition is true -->np.argwhere(logic)  
# 10.apply transpose --> arr.T
# 11.check the diagonal elements --> np.diag()
# 12.compute inverse of an array --> np.linalg.inv()
# 13.how to reshape an array --> np.reshape(rows,col)
# 14.concatenate 2 array --> np.concatenate((arr1,arr2),axis=0/1)
# 15.how to copy an array --> np.copy()

In [1]:
 # Broadcasting a Scalar to a 1D Array
import numpy as np
arr=np.array([1,2,4,5])
res=arr+1
print(res)

[2 3 5 6]


In [3]:
# Broadcasting a 1D Array to a 2D Array
import numpy as np
a=np.array([2,4,6])
b=np.array([[5,10,15],[20,30,40]])
res=a+b
print(res)

[[ 7 14 21]
 [22 34 46]]


In [7]:
# Broadcasting in Conditional Operations
import numpy as np
a=np.array([18,21,13,23,15])
b=np.array(["Adult","Minor"])

res=np.where(a>=18,b[0],b[1])
print(res)

['Adult' 'Adult' 'Minor' 'Adult' 'Minor']


In [8]:
# Using Broadcasting for Matrix Multiplication
import numpy as np
a=np.array([2,4,6])
b=np.array([5,10,15])
res=a*b
print(res)

[10 40 90]


In [19]:
 # Scaling Data with Broadcasting
import numpy as np
fd = np.array([[0.2, 2.5, 3.9],
                [52.4, 23.6, 36.5],
                [55.2, 31.7, 23.9],
                [14.4, 11.0, 4.9]])
cpg=np.array([2,3,4])

res=fd*cpg
print("Multiplication is \n",res)

Multiplication is 
 [[  0.4   7.5  15.6]
 [104.8  70.8 146. ]
 [110.4  95.1  95.6]
 [ 28.8  33.   19.6]]


In [27]:
# Adjusting Temperature Data Across Multiple Locations
import numpy as pd
temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])

arr=np.array([1.5,-0.5,2.0])
res=temp+arr[:, None]
print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [32]:
 # Normalizing Image Data
import numpy as np
img = np.array([ [1000, 120, 130],
                 [900, 110, 140],
                 [80, 100, 120]])

m=img.mean(axis=0)
n=img.std(axis=1)

res=(img-m)/n
print(res)

               

[[ 0.82424411  0.02735651  0.        ]
 [ 0.58181937  0.          0.61237244]
 [-1.40606348 -0.02735651 -0.61237244]]


In [42]:
# Centering Data in Machine Learning
import numpy as np
data=np.array([[10,20,],
             [15,25],
             [20,30]])
m=data.mean(axis=0)
res=data-m
print(res)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
