In [2]:
import numpy as np
print(np.zeros(5).dtype)

float64


In [3]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

b=a
b is a

True

In [5]:
res=np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print(res)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [6]:
a=np.array([[1,2],[3,5]])
a.ndim

2

In [10]:
a=np.matrix([1,2,3])
b=np.matrix([1,2,3])
res=np.concatenate((a,b))
print(res)

[[1 2 3]
 [1 2 3]]


In [11]:
res=np.create((3,3))
print(res)

AttributeError: module 'numpy' has no attribute 'create'

In [12]:
r1=np.array([1,2])
r2=np.array([3,4])
res=r1*r2
print(res)

[3 8]


In [14]:
res=np.dot([1,2],[3,4])
print(res)

11


In [19]:
res=np.array([10,20,30,40])
print(res.itemsize)

4


In [21]:
res=np.linspace(1,5,5)
print(res)

[1. 2. 3. 4. 5.]


In [22]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


In [28]:
a=np.array[a1,a2,a3]
b=np.array[b1,b2,b3]

res=np.dot(a,b)
print(res)


NameError: name 'a1' is not defined

In [3]:
import numpy as np

color_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])

print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [1]:
import numpy as np

with np.errstate(all='ignore'):
    x = np.array([1, 0, -1])
    y = x / 0
    print(y)


[ inf  nan -inf]
