In [2]:
# what is numpy
# It is a core library for scientific computing in python.
# The central object in numpy is Numpy Array's

# what is Numpy Array's
# High performance multidimenstional objects which is disgned for the methematical operations.

#How many types of Numpy array's?
#1D-Array:- An array with specific rows(axis = 0) and no columns
#2D-Array:- An array with speficc rows and columns(axis= 0 and axis = 1)
#3D-Array:- An array with multidimensions(rows, columns, partitions)


In [ ]:
#what are all use cases and mathematical operations achevied by using Numpy?
"""
1.Dot product/Inner Product (Linear and logistic regression works on dot product)
2.Matrix multiplication
3.Solving the linear systems
4.Inverse
5.determinent
6.choose the random numbers
7.statistics """

In [4]:
# Basic of Numpy of Array.
import numpy as np
a=[1,2,3,4,6]
arr=np.array(a)

print("List in Pyhton",a)
print("Numpy array in python",arr)


print(type(a)) # List
print(type(arr))# Numpy array

List in Pyhton [1, 2, 3, 4, 6]
Numpy array in python [1 2 3 4 6]
<class 'list'>
<class 'numpy.ndarray'>


In [2]:
#what is pip?
#pip is a python package manager used to install new packages into python
# !pip install numpy

#import the library
import numpy as np

#check the vesrion of the Numpy
np.__version__

'1.26.4'

In [5]:
# The central object in nupy is Numpy Array

#How can we create an array?
#Array's can be created from the existing data
l = [1,2,3,4,5]
#convert the list into an array
a = np.array(l)
print(a)
#find the number of rows and columns in array
a.shape
#find the number of elements in the array
a.size
#find the dimensionality of an array?
a.ndim
#find the data type pf each element inside the array
a.dtype
#find the storage of each elementgs in bytes in the array
a.itemsize

[1 2 3 4 5]


4

In [13]:
#Array's are defined as ordered, immutable, and allows the duplicate data

# Essential Methods in Numpy

# Access the element from numpy
l=[10,20,40,50,60]
# print "20" from the above array
print(l[1])
# print the reverse the entire array
print(l[::-1])
# print the l
print(l[:])

#In array we can replace the data but we cannot add and remove the data
#replace "50" with "5"
l[3] = 5
print(l)

20
[60, 50, 40, 20, 10]
[10, 20, 40, 50, 60]
[10, 20, 40, 5, 60]


In [22]:
# Element wise maths operation
import numpy as np
b=[2,3,4,5]
c=np.array([10,20,30,40])
# print(b+c)


d=np.array([5,10,20,30])
# print the sum of element in above array
print(d.sum())
#print the max of element in above array
print(d.max())
#print the min of element in above array
print(d.min())

65
30
5


In [35]:
#what is vector addition?
#when we apply an addition on array's of same length or same size is known as vector addition

# what is difference between array's and list
list=[5,10,15,20]
n=np.array(list)
# add "25" into above list
list.append(25)
print(list)


# end the new a item into array "e"
# n.append(25)
# print(n)# AttributeERROR   


f=n+np.array(25)
print(f)


[5, 10, 15, 20, 25]
[30 35 40 45]


In [41]:
"""when we add a single element array to the existing array of different size then the new array element 
is going add up with each element in exisiting array this method is known as "Broadcasting method
"""

#Normal way broadcasting-method
square=[1,2,3,4,5,6]
#print above list with product of 2
for i in square:
    print(i*2,end=" ")


# way to broadcasting-method 
bc=np.array(square)
print(bc*2)

2 4 6 8 10 12 [ 2  4  6  8 10 12]


In [43]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
#combine the above 2 arrays
arr3 = np.append(arr1,arr2)
print(arr3)


#find the sqrt of arr1
print(np.sqrt(arr1))

[ 1  2  3  4  5  6  7  8  9 10]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [49]:
# Dot product
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
dot=0

for i in range(len(a)):
    dot+=a[i]*b[i]
print(dot)    

11


In [69]:
#define dot product?
#vector multiplication of array's and sum  of the result
#multiply each corresponding element and do the sum

# easy with numpy
dot=np.dot(a,b)
print(dot)

#manual method
c=a*b
print(c)

d=np.sum(c)
print(d)

e=a.dot(b)
print(e)

#create an array with set
s={20,30,40,50}
print(np.array(s))

11
[3 8]
11
11
{40, 50, 20, 30}


In [8]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
#print the entire first column
print(a)
# print the second row
print(a[1])

[[1 2 3]
 [4 5 6]]
[4 5 6]


In [2]:
import numpy as np
arr=np.array([[[1,2,4],
             [4,5,6],
              [6,7,8]]])
print(arr)
arr.ndim

[[[1 2 4]
  [4 5 6]
  [6 7 8]]]


3