In [1]:
# Random Number 
# generate an random numbers uniformally distributed with 3 rows and 2 colums
import numpy as np
a=np.random.random((3,2))
print(a)

[[0.26032537 0.28820073]
 [0.59302165 0.36030055]
 [0.8771143  0.35581084]]


In [4]:
# generate an array which is normally distributed
import numpy as np
b=np.random.randn(1000)
# print(b)

#How can we say an array is normally distributed
print(b.mean(),b.std())

-0.031319915569685323 0.9649876217930549


In [6]:
# generate an normally distributed data with 100rows and 3columns.
import numpy as np
c=np.random.randn(100,3)
print(c)

[[ 0.02189904  1.50192378 -0.46978071]
 [-0.9172841  -1.39409525  0.56349115]
 [-1.74578983  0.96920211 -0.4001937 ]
 [-0.38578182 -0.49151464 -0.83911465]
 [-0.57627061  0.40905968 -2.48001689]
 [-2.15198839 -1.3483904  -1.15408648]
 [ 0.41952097 -0.03911348  0.8226366 ]
 [ 1.25801562 -1.35459555 -1.44411463]
 [ 0.85303662  1.35473063 -1.50450949]
 [-0.47282408 -1.21765379 -0.80024091]
 [-0.1976349   0.05561309  0.79143768]
 [-0.90957123 -0.65959461  0.87479809]
 [ 0.41726117 -0.28238445 -0.08002698]
 [-2.06409512  0.48150857  0.14497867]
 [ 1.16569635 -1.5132874  -1.37394394]
 [ 1.09249504 -1.15795768 -0.30563967]
 [-0.63234877  1.81382586 -0.14336536]
 [-0.9733252  -0.90637821 -0.76212384]
 [-2.05418156 -0.17191538  0.07239343]
 [-0.58408853 -0.24878226  0.69978453]
 [-0.33578332 -1.07425998 -0.13339098]
 [-0.03385816 -0.41040126  0.13909407]
 [-1.3119414  -0.70375908 -0.2861319 ]
 [ 1.67056889 -0.59202627  0.73588087]
 [ 0.03849681  0.23584287  0.6176479 ]
 [ 1.21577791  0.13096124

In [39]:
#generate an array in random integer.
import numpy as np
i=np.random.randint(1,10,size=())
print(i)

[[7 5]
 [2 4]
 [3 4]]
