In [6]:
# Reshapping an a array

# Create an array of numpy range 10
import numpy as np
a=[0,1,2,3,4,5,6,7,8,9]
a=np.arange(10)

print(a)

SyntaxError: invalid syntax (1736247208.py, line 3)

In [10]:
# converts the above array to 5 rows and 2columns
b=a.reshape(5,2)
print(b)

print(b.T) 
# np.reshape(row,col)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [22]:
# Concatenation
a=np.array([[1,2],[3,4]])
b=np.array([[5,7],[8,9]])

c=np.concatenate((a,b),axis=0) # axis=0 -->columns  ,axis=1 -->rows
print(c)



[[1 2]
 [3 4]
 [5 7]
 [8 9]]
