In [4]:
# Hstack
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,7],[8,9]])

c=np.hstack((a,b))
print(c)

[[1 2 5 7]
 [3 4 8 9]]


In [3]:
# Vstack
a=np.array([[1,2],[3,4]])
b=np.array([[5,7],[8,9]])

d=np.vstack((a,b))
print(d)

[[1 2]
 [3 4]
 [5 7]
 [8 9]]
