In [3]:
# Transpose: transpose converts rows into columns and vice verse
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
# convert the transpose element
print(a.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
Dot-Product matrix multipliction